// ONBOARDING

export const USER_ACTIVE = 'USER_ACTIVE';
export const USER_INACTIVE = 'USER_INACTIVE';

export const FT_USER = 'FT_USER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';

export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP SUCCESS';

export const AUTH_ERROR = 'AUTH ERROR';
export const LOGIN_ERROR = 'LOGIN ERROR';
export const SIGNUP_ERROR = 'SIGNUP ERROR';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';
